---
collections:
  - name: git+https://github.com/snehald12/Proj.git
    type: git
    version: main



#---
#collections:
#   - netapp.um_info 
#   - ibm.power_aix

#  - name:  community.general
#    version: 7.5.3
#  - vmware.vmware_rest
#  - community.vmware
