---
- name: test play
  hosts: localhost
  connection: local
  tasks:
     - name: test
       debug: 
           msg: "Hello"
       tags:
           - hello
           
     - name: ping
       ping:
       tags:
           - ping
