- name: Configure Controller in environment 
  hosts: all
  connection: local
  gather_facts: no

  collections:
    - ansible.controller
    - redhat_cop.controller_configuration

  vars:
    controller_hostname: 65.2.175.153
    controller_validate_certs: False

  tasks:
    - include_role:
        name: redhat_cop.controller_configuration.organizations
    - include_role:
       name: redhat_cop.controller_configuration.users
    - include_role:
        name: redhat_cop.controller_configuration.teams
    
