- name: Configure Controller in environment 
  hosts: all
  connection: local
  gather_facts: no

  collections:
    - ansible.controller
    - redhat_cop.controller_configuration

  vars:
    controller_hostname: 65.2.175.153
    controller_validate_certs: False

  tasks:
    - controller_meta:
      register: result
    
