---
- name: kevintest
  host: cor089xa091
  gather_facts: false
  tasks:
    - name: run check cmd
      ansible.builtin.shell: "/usr/mqm/bin/setmqenv -s ; /usr/mqm/bin/dspmq -m CORTSADM1"
      register: dspmq_out

    -  name: Display command output
       debug:
         var: dspmq_out.stdout_lines
