---
- name: test
  hosts: localhost

  tasks:
    - name: get cred details
      ansible.controller.project:
        name: "p1"
        organization: "Default"
        state: exists
      register: p1_details
