---
- name: test
  hosts: localhost
  collections:
      - ansible.controller

  tasks:
    - name: get cred details
      project:
        name: "p1"
        organization: "Default"
        state: exists
