- hosts: localhost
  gather_facts: false
  become: yes
  become_user: test
  
  tasks:
     - action: ping
     
     - command: whoami
       register: output
       
     - debug: 
         msg: "{{ output.stdout }}"
