- hosts: 192.168.122.248
  gather_facts: true
  become: yes
  become_user: test
  
  tasks:
     - action: ping
     
     - command: whoami
       register: output
       
     - debug: 
         msg: "{{ output.stdout }}"
