---
- name: test playbook
  hosts: all
  collections:
     - amazon.aws
  tasks:

   - name: Gather information about all instances in AZ ap-southeast-2a
     amazon.aws.ec2_instance_info:
      region: ap-south-1
      filters:
          availability-zone: ap-south-1a
