- hosts: localhost
  gather_facts: true
  become: yes
  become_user: test
  become_method: sudo
  anisble_sudo_pass: 12
  
  tasks:
     - action: ping
     
     - command: whoami
       register: output
       
     - debug: 
         msg: "{{ output.stdout }}"
