---
- name: test playbook
  hosts: ip-10-0-15-145.ap-south-1.compute.internal
  collections:
     - amazon.aws
  tasks:

   - name: Gather information about all instances in AZ ap-south-1a
     amazon.aws.ec2_instance_info:
      region: ap-south-1
      filters:
          availability-zone: ap-south-1a
