---
- name: test
  hosts: localhost

  tasks:
    - name: get cred details
      credential:
        name: "Automation Hub Published Repository"
        organization: "Default"
        credential_type: "Ansible Galaxy/Automation Hub API Token"
        state: exists
      register: hub_cluster_aap_creds
