---
- name: test
  hosts: all
  tasks:
     - name: This is my First Demo
       shell:
         cmd: ansible-galaxy collection list
       register: result
       
     - name: print msg
       debug:
         var: result
       
         #no_log: true
   #  - name: This is Demo
   #    debug:
   #      msg: "Hello {{full_name}}"    
   #  - name: ping all
   #    ping:
