---
- name: Hello Git
  hosts: all
  vars: 
     nickname:
     fullname:
  tasks:
     - name: This is my First Demo
       debug:
         msg: "Hello {{nickname}}:{{fullname}}"
   #  - name: This is Demo
   #    debug:
   #      msg: "Hello {{full_name}}"    
   #  - name: ping all
   #    ping:
