---
- name: Hello Git
  hosts: all
  vars: 
     nick_name:
     full_name:
  tasks:
     - name: This is my First Demo
       debug:
         msg: "Hello {{nick_name}}:{{full_name}}"
       #no_log: true
   #  - name: This is Demo
   #    debug:
   #      msg: "Hello {{full_name}}"    
   #  - name: ping all
   #    ping:
