---
- name: test
  hosts: localhost
  tasks:
     - name: This is my First Demo
       shell:
         cmd: ansible-galaxy collection list
         #no_log: true
   #  - name: This is Demo
   #    debug:
   #      msg: "Hello {{full_name}}"    
   #  - name: ping all
   #    ping:
