---
- name: test playbook
  hosts: localhost
  tasks:
    - name: Create a Directory /root
      file:
        path: /root/test/
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Git checkout
      ansible.builtin.git:
        repo: https://<username>:<password>h@github.com/proj.git
        dest: /root/test/
