---
- name: test playbook
  hosts: localhost
  vars_files:
    - pssing.yml
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: https://{{username}}:{{token}}@github.com/snehal/proj.git
        dest: /var/lib/awx/test/
