---
- name: Install update package
  hosts: all
  tasks:
   - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
     ansible.windows.win_updates:
        category_names: "*"
        state: searched
        log_path: C:\ansible_wu.txt
        
     #- name: Install all updates and reboot as many times as needed
     #  ansible.windows.win_updates:
     #     category_names: "*"
     #     reboot: yes
    
    
    
